# -*- coding: utf-8 -*-
"""Harshika.S_AI/ML_Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFFfCQ4yzSVCcjPzi5yznr1xB97zZ4RY
"""

# 1. Accept two numbers from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# 2. Perform basic arithmetic operations
add = num1 + num2
subtract = num1 - num2
multiply = num1 * num2
divide = num1 / num2
modulus = num1 % num2
power = num1 ** num2

# 3. Demonstrate comparison and logical operators
greater = num1 > num2
less = num1 < num2
equal = num1 == num2
not_equal = num1 != num2
logical_and = (num1 > 0) and (num2 > 0)
logical_or = (num1 > 0) or (num2 > 0)
logical_not = not(num1 > num2)

# 4. Print results clearly using formatted output (f-strings)
print("\n--- Arithmetic Operations ---")
print(f"Addition: {num1} + {num2} = {add}")
print(f"Subtraction: {num1} - {num2} = {subtract}")
print(f"Multiplication: {num1} * {num2} = {multiply}")
print(f"Division: {num1} / {num2} = {divide}")
print(f"Modulus: {num1} % {num2} = {modulus}")
print(f"Power: {num1} ** {num2} = {power}")

print("\n--- Comparison Operators ---")
print(f"{num1} > {num2}: {greater}")
print(f"{num1} < {num2}: {less}")
print(f"{num1} == {num2}: {equal}")
print(f"{num1} != {num2}: {not_equal}")

print("\n--- Logical Operators ---")
print(f"({num1} > 0) and ({num2} > 0): {logical_and}")
print(f"({num1} > 0) or ({num2} > 0): {logical_or}")
print(f"not({num1} > {num2}): {logical_not}")

import random
import numpy as np

# 1. Create a list of 10 random integers between 1 and 100
numbers = [random.randint(1, 100) for _ in range(10)]
print("Original List:", numbers)

# 2. Perform various operations

# Add and remove elements
numbers.append(55)  # Add element
print("\nAfter adding 55:", numbers)

numbers.remove(numbers[0])  # Remove the first element
print("After removing the first element:", numbers)

# Find maximum and minimum values
max_val = max(numbers)
min_val = min(numbers)
print(f"\nMaximum Value: {max_val}")
print(f"Minimum Value: {min_val}")

# Sort the list
numbers.sort()
print("Sorted List:", numbers)

# 3. Convert the list into a NumPy array
arr = np.array(numbers)
print("\nNumPy Array:", arr)

# Calculate Mean, Median, and Standard Deviation
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print(f"\nMean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev:.2f}")

# 1. Create a dictionary named student with keys: name, course, marks
student = {
    "name": "Harshi",
    "course": "Electronics and Communication Engineering",
    "marks": 85
}

# 2. Add a new key 'grade' based on marks
if student["marks"] >= 90:
    student["grade"] = "A"
elif student["marks"] >= 75:
    student["grade"] = "B"
elif student["marks"] >= 60:
    student["grade"] = "C"
else:
    student["grade"] = "D"

# 3. Print all keys and values using a loop
print("--- Student Details ---")
for key, value in student.items():
    print(f"{key.capitalize()}: {value}")

# 4. Create two sets of AI tools
set1 = {"ChatGPT", "Copilot", "Bard", "Claude"}
set2 = {"ChatGPT", "Gemini", "Claude", "Perplexity"}

# Perform set operations
print("\n--- AI Tools Set Operations ---")
print(f"Set 1: {set1}")
print(f"Set 2: {set2}")

# Union
print(f"Union: {set1 | set2}")

# Intersection
print(f"Intersection: {set1 & set2}")

# 1. Create a text file named ai_students.txt and write details of 5 students
students = [
    {"name": "Harshi", "marks": 85, "grade": "B"},
    {"name": "Aarav", "marks": 92, "grade": "A"},
    {"name": "Diya", "marks": 74, "grade": "C"},
    {"name": "Kiran", "marks": 68, "grade": "C"},
    {"name": "Ravi", "marks": 88, "grade": "B"}
]

# Write data to file
with open("ai_students.txt", "w") as file:
    file.write("Name\tMarks\tGrade\n")
    for s in students:
        file.write(f"{s['name']}\t{s['marks']}\t{s['grade']}\n")

print("✅ Data written to 'ai_students.txt' successfully.\n")

# 2. Read the file and display students who scored above 75 marks
print("--- Students who scored above 75 ---")

with open("ai_students.txt", "r") as file:
    next(file)
    for line in file:
        name, marks, grade = line.strip().split("\t")
        if int(marks) > 75:
            print(f"Name: {name}, Marks: {marks}, Grade: {grade}")

import datetime

# 1. Accept user input
prompt = input("Enter your AI prompt: ")

# 2. Get the current timestamp
timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# 3. Save the prompt text in a file named prompt_history.txt
with open("prompt_history.txt", "a") as file:
    file.write(f"[{timestamp}] {prompt}\n")

print("✅ Prompt saved successfully to 'prompt_history.txt'.")